name: Test Artifact Upload

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create dummy file
        run: |
          mkdir myapp
          echo "Hello from build" > myapp/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp

      - name: Show downloaded file
        run: dir ./myapp
